version: '3.7'
services:
  site:
    image: dronico/site:latest
    build: .
    container_name: site
    expose:
      - "3000"
    network_mode: bridge
    environment:
      - VIRTUAL_HOST=droni.co,www.droni.co
      - LETSENCRYPT_HOST=droni.co,www.droni.co
      - LETSENCRYPT_EMAIL=dev@droni.co
      - VIRTUAL_PORT=3000
